# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motioncontroller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='motioncontroller.proto',
  package='motioncontroller',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16motioncontroller.proto\x12\x10motioncontroller\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\rCommandResult\x12\x16\n\x0e\x63ommand_result\x18\x01 \x01(\t\"?\n\x0e\x44igital2Analog\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\x17\n\x0f\x63hannel_voltage\x18\x02 \x01(\x02\"&\n\x0e\x41nalog2Digital\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\"7\n\x14\x41nalog2DigitalConfig\x12\x0c\n\x04gain\x18\x01 \x01(\x05\x12\x11\n\tdata_rate\x18\x02 \x01(\x05\".\n\x18SetDiffChnAnalog2Digital\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x32\xc5\x03\n\rDeviceService\x12J\n\x08SayHello\x12\x1e.motioncontroller.HelloRequest\x1a\x1c.motioncontroller.HelloReply\"\x00\x12N\n\x10GetDigitalValues\x12\x16.google.protobuf.Empty\x1a .motioncontroller.Analog2Digital\"\x00\x12Q\n\nOutVoltage\x12 .motioncontroller.Digital2Analog\x1a\x1f.motioncontroller.CommandResult\"\x00\x12\x64\n\x17\x43onfigureAnalog2Digital\x12&.motioncontroller.Analog2DigitalConfig\x1a\x1f.motioncontroller.CommandResult\"\x00\x12_\n\x0eSetDiffChannel\x12*.motioncontroller.SetDiffChnAnalog2Digital\x1a\x1f.motioncontroller.CommandResult\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='motioncontroller.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='motioncontroller.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=101,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='motioncontroller.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='motioncontroller.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=132,
)


_COMMANDRESULT = _descriptor.Descriptor(
  name='CommandResult',
  full_name='motioncontroller.CommandResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_result', full_name='motioncontroller.CommandResult.command_result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=173,
)


_DIGITAL2ANALOG = _descriptor.Descriptor(
  name='Digital2Analog',
  full_name='motioncontroller.Digital2Analog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='motioncontroller.Digital2Analog.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='channel_voltage', full_name='motioncontroller.Digital2Analog.channel_voltage', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=238,
)


_ANALOG2DIGITAL = _descriptor.Descriptor(
  name='Analog2Digital',
  full_name='motioncontroller.Analog2Digital',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_name', full_name='motioncontroller.Analog2Digital.channel_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=278,
)


_ANALOG2DIGITALCONFIG = _descriptor.Descriptor(
  name='Analog2DigitalConfig',
  full_name='motioncontroller.Analog2DigitalConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gain', full_name='motioncontroller.Analog2DigitalConfig.gain', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data_rate', full_name='motioncontroller.Analog2DigitalConfig.data_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=335,
)


_SETDIFFCHNANALOG2DIGITAL = _descriptor.Descriptor(
  name='SetDiffChnAnalog2Digital',
  full_name='motioncontroller.SetDiffChnAnalog2Digital',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='motioncontroller.SetDiffChnAnalog2Digital.channel_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=383,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['CommandResult'] = _COMMANDRESULT
DESCRIPTOR.message_types_by_name['Digital2Analog'] = _DIGITAL2ANALOG
DESCRIPTOR.message_types_by_name['Analog2Digital'] = _ANALOG2DIGITAL
DESCRIPTOR.message_types_by_name['Analog2DigitalConfig'] = _ANALOG2DIGITALCONFIG
DESCRIPTOR.message_types_by_name['SetDiffChnAnalog2Digital'] = _SETDIFFCHNANALOG2DIGITAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

CommandResult = _reflection.GeneratedProtocolMessageType('CommandResult', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDRESULT,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.CommandResult)
  })
_sym_db.RegisterMessage(CommandResult)

Digital2Analog = _reflection.GeneratedProtocolMessageType('Digital2Analog', (_message.Message,), {
  'DESCRIPTOR' : _DIGITAL2ANALOG,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.Digital2Analog)
  })
_sym_db.RegisterMessage(Digital2Analog)

Analog2Digital = _reflection.GeneratedProtocolMessageType('Analog2Digital', (_message.Message,), {
  'DESCRIPTOR' : _ANALOG2DIGITAL,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.Analog2Digital)
  })
_sym_db.RegisterMessage(Analog2Digital)

Analog2DigitalConfig = _reflection.GeneratedProtocolMessageType('Analog2DigitalConfig', (_message.Message,), {
  'DESCRIPTOR' : _ANALOG2DIGITALCONFIG,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.Analog2DigitalConfig)
  })
_sym_db.RegisterMessage(Analog2DigitalConfig)

SetDiffChnAnalog2Digital = _reflection.GeneratedProtocolMessageType('SetDiffChnAnalog2Digital', (_message.Message,), {
  'DESCRIPTOR' : _SETDIFFCHNANALOG2DIGITAL,
  '__module__' : 'motioncontroller_pb2'
  # @@protoc_insertion_point(class_scope:motioncontroller.SetDiffChnAnalog2Digital)
  })
_sym_db.RegisterMessage(SetDiffChnAnalog2Digital)



_DEVICESERVICE = _descriptor.ServiceDescriptor(
  name='DeviceService',
  full_name='motioncontroller.DeviceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=386,
  serialized_end=839,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='motioncontroller.DeviceService.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDigitalValues',
    full_name='motioncontroller.DeviceService.GetDigitalValues',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_ANALOG2DIGITAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='OutVoltage',
    full_name='motioncontroller.DeviceService.OutVoltage',
    index=2,
    containing_service=None,
    input_type=_DIGITAL2ANALOG,
    output_type=_COMMANDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigureAnalog2Digital',
    full_name='motioncontroller.DeviceService.ConfigureAnalog2Digital',
    index=3,
    containing_service=None,
    input_type=_ANALOG2DIGITALCONFIG,
    output_type=_COMMANDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetDiffChannel',
    full_name='motioncontroller.DeviceService.SetDiffChannel',
    index=4,
    containing_service=None,
    input_type=_SETDIFFCHNANALOG2DIGITAL,
    output_type=_COMMANDRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEVICESERVICE)

DESCRIPTOR.services_by_name['DeviceService'] = _DEVICESERVICE

# @@protoc_insertion_point(module_scope)
